title_name = "The Orange Box"
title_id = "4541080F" # EA-2063
hash = "B3D3A97499F8785B" # default.xex
#media_id = "651A85DA" # Disc (World): http://redump.org/disc/11838

[[patch]]
    name = "-dvd"
    desc = "Same as adding -dvd to cl in the Xenia Canary config. Prevents crashing, but you still need to pass '-game hl2/episodic/ep2/portal/tf'"
    author = "Margen67"
    is_enabled = true

    [[patch.be32]]
        address = 0x82010968
        value = 0x60000000 # 0x419a002c
